INSERT INTO CLIENTE (IDENTIFICACION, NOMBRE, APELLIDOS, PAIS_RESIDENCIA, PAIS_NACIMIENTO, DIRECCION,TELEFONO) VALUES ('112970420', 'MAX', 'ACEVEDO', 'CR', 'CR','RAMON','71082859','true');
INSERT INTO CLIENTE (IDENTIFICACION, NOMBRE, APELLIDOS, PAIS_RESIDENCIA, PAIS_NACIMIENTO, DIRECCION,TELEFONO) VALUES ('565656555', 'REINER', 'ROJAS', 'CR', 'CR','SAN RAMON','5555555','true');
INSERT INTO CLIENTE (IDENTIFICACION, NOMBRE, APELLIDOS, PAIS_RESIDENCIA, PAIS_NACIMIENTO, DIRECCION,TELEFONO) VALUES ('666565555', 'MARLON', 'SOTO', 'CR', 'CR','SAN ISIDRO','66654444','true');
